/** Nomes de bancos para seleção no formulário PIX (exibição apenas). */
export const BRAZILIAN_BANK_NAMES: string[] = [
  'Banco do Brasil',
  'Bradesco',
  'Itaú',
  'Santander',
  'Caixa Econômica Federal',
  'Nubank',
  'Inter',
  'C6 Bank',
  'BTG Pactual',
  'Original',
  'Mercado Pago',
  'PicPay',
  'PagBank (PagSeguro)',
  'Sicredi',
  'Sicoob',
  'Banrisul',
  'Banco Safra',
  'Banco Pan',
  'Banco Votorantim',
  'Banco Modal',
  'Neon',
  'Will Bank',
  'Stone',
  'Outro',
]
